name: app_mobile
description: Ứng dụng của ECOIT

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  # font
  font_awesome_flutter: ^9.1.0
  google_fonts: ^2.1.0

  # share preferences
  shared_preferences: ^2.0.7

  # dateTime picker
  flutter_datetime_picker: ^1.5.1

  # format dates
  intl: ^0.17.0

  # regex pattern
  regexpattern: ^2.0.1

  # svg image
  flutter_svg: ^0.22.0

  # loader overlay
  loader_overlay: ^2.0.2+1
  flutter_easyloading: ^3.0.3

  # bottom navigation
  curved_navigation_bar: ^1.0.1

  # input OTP
  pin_code_fields: ^7.3.0

  # captcha
  hb_check_code: ^0.0.2

  # hive database
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  # slider
  carousel_slider: ^4.0.0

  # file picker
  file_picker: ^4.1.3

  # bloc pattern
  flutter_bloc: ^7.3.0
  rxdart: ^0.27.2

  # provider pattern
  provider: ^6.0.1

  # toast message
  toast: ^0.1.5

  # auto completed
  flutter_typeahead: ^3.2.1

  # modal bottom sheet
  modal_bottom_sheet: ^2.0.0

  # firebase
  firebase_core: ^1.7.0
  firebase_messaging: ^10.0.8
  flutter_local_notifications: ^9.0.0

  #PDF view
  flutter_pdfview: ^1.2.1
  syncfusion_flutter_pdfviewer: ^19.3.45-beta

  #video player
  video_player: ^2.2.5
  chewie: ^1.0.2

  # photo view
  photo_view: ^0.13.0

  # popup
  popover: ^0.2.6+3

  # check type file
  mime: ^1.0.0

  # dio
  dio: ^4.0.0

  # getX
  get: ^4.3.8

  # view document
  url_launcher: ^6.0.12
  open_file: ^3.2.1

  # chart
  fl_chart: ^0.40.2

  # timeline
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
      - assets/images/
      - assets/icons/

  fonts:
     - family: Roboto
       fonts:
         - asset: assets/fonts/Roboto/Roboto-Light.ttf
           weight: 500

         - asset: assets/fonts/Roboto/Roboto-Bold.ttf
           weight: 700

         - asset: assets/fonts/Roboto/Roboto-Medium.ttf
           weight: 300

