import 'package:flutter/material.dart';
const Color kThirtColor = Color(0xFFFFECC0);
const Color kSecondColor = Color(0xFFFFECDF);
const Color kPrimaryColors = Color(0xfff2861e)  ;
const Color kWhiteColors = Colors.white;
const Color kBlackColors = Colors.black;
const Color kGreyColors = Colors.grey;
const Color kLabelColors = Colors.black54;
const Color login_bg = Color(0x3107c41);
const Color signup_bg = Color(0xff000a54);
const kWarningColor = Color(0xFFF3BB1C);
const kErrorColor = Color(0xFFF03738);
const kTextColor = Color(0xFF757575);
const kSuccessColor = Color(0xFF42BA96);